# This is a basic workflow that is manually triggered

name: License Check

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
  workflow_dispatch:
   

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  check:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Collect module licenses
      run: mvn clean install -DskipTests
    - name: Collect module licenses
      run: mvn license:add-third-party
    - name: Aggregate licenses
      run: mvn license:aggregate-add-third-party
    - name: Set script permissions
      run: chmod u+x .github/workflows/license-check/license-check.sh
    - name: Run script
      run: .github/workflows/license-check/license-check.sh
      #continue-on-error: true
